### ISSUE TITLE
Design minimal data structure

### ISSUE THREAD

**Issue by pombredanne** [spdx/package-licenses-mapping#1]
This is a continuation of https://github.com/spdx/tools-python/issues/106

**Comment by pombredanne** [comment]
@sschuberth @nishakm Here is a suggested structure.

Given these:
- a license string and or structured data snippet (to account for npm old styles and Maven <licenses> structures) as found in a package manifest. 
- a package manager type (e.g. a Package URL type)


Then we map to:
- a SPDX license expression
- some indication of confidence (say between 0 and 100) for the accuracy of this mapping, defaulting to 100.
- some optional notes


And here would be an example using a YAML serialization:
```
- package_type: npm
  declared_license:
    license: MIT
  license_expression: MIT

- package_type: maven
  declared_license:
    name: Apache License, Version 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  license_expression: Apache-2.0
  notes: See https://repo1.maven.org/maven2/org/springframework/hateoas/spring-hateoas/0.15.0.RELEASE/spring-hateoas-0.15.0.RELEASE.pom  

- package_type: pypi
  declared_license:
    license: http://creativecommons.org/publicdomain/zero/1.0/
    classifiers: 'License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication'
  license_expression: CC0-1.0
  notes: See https://github.com/dchest/pyblake2/blob/master/setup.py for example

- package_type: pypi
  declared_license:
    classifiers: 'License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication'
  license_expression: CC0-1.0
  notes: See https://github.com/dchest/pyblake2/blob/master/setup.py for example

- package_type: npm
  declared_license:
    license: bsd
  license_expression: BSD-3-Clause
  confidence: 80

```

**Comment by nishakm** [comment]
@pombredanne where does the confidence number come from? Is it something vetted by the legal community somewhere? It would be nice to include those numbers for all of the package_type and license combinations.

**Comment by pombredanne** [comment]
Another example for http://central.maven.org/maven2/com/sun/xsom/xsom/20100725/xsom-20100725.pom (from https://github.com/spdx/tools-python/issues/106#issuecomment-499911725 )
```
- package_type: maven
  declared_license: 
    license:
      name: CDDL v1.0 / GPL v2 dual license
      url: https://glassfish.dev.java.net/nonav/public/CDDL+GPL.html
  license_expression: CDDL-1.0 OR GPL-2.0-only

- package_type: maven
  declared_license: 
    license:
      name: CDDL v1.1 / GPL v2 dual license
      url: https://glassfish.java.net/public/CDDL+GPL_1_1.html
  license_expression: CDDL-1.1 OR GPL-2.0-only
```

**Comment by pombredanne** [comment]
@nishakm re: https://github.com/spdx/package-licenses-mapping/issues/1#issuecomment-535037645
> where does the confidence number come from? Is it something vetted by the legal community somewhere? 

That's just a rough evaluation provided by someone contributing a data point. I am fine to have legal folks validating this if they like, but I would not want this to be a gating item.

> It would be nice to include those numbers for all of the package_type and license combinations.

As suggested here, it would default to 100 if not provided, so it would be always "there" yet would not need to be repeated if this has the default value.

**Comment by pombredanne** [comment]
BTW this brings up the issue of things that do not exist in SPDX such as Public domain, proprietary licenses, etc... all things that do exist in the wild in package manifest declarations.

**Comment by pombredanne** [comment]
Also of note:
- I would consider that the case, spacing and punctuation of the declared licenses data to have no significance (with the possible exception of the `+` sign)
- we may need to consider the Package URL type and namespace in some cases. For instance, for RPM distros the conventions used in Fedora and Suse are different and may not overlap gracefully... TBD, we can wait to add this when the problem comes up.

**Comment by sschuberth** [comment]
> some indication of confidence (say between 0 and 100) for the accuracy of this mapping

I'm actually against a confidence and would only add uncontroversial mappings. It's generally too opaque how such a confidence level is calculated, and how to determine a suitable threshold for your particular use-case.

**Comment by goneall** [comment]
Any issue with using JSON rather than YAML?  

If we are intending this to be primarily machine read, JSON is reported to have a higher adoption rate as a serialization format.  (reference https://twobithistory.org/2017/09/21/the-rise-and-rise-of-json.html) while YAML has an advantage in being more human readable.

If this was intended to be primarily human read and/or written (e.g. like a configuration file), I would agree with YAML.  I think this will be primarily read by tools so JSON may be a better choice.

BTW - I don't feel strongly - I can use either format in the Java tooling, just throwing this out there before we lock down the format.

**Comment by goneall** [comment]
> BTW this brings up the issue of things that do not exist in SPDX such as Public domain, proprietary licenses, etc... all things that do exist in the wild in package manifest declarations.

We could add "local licenses" for each section into the document using the same terms as section [6.1 in the spec](https://spdx.org/spdx-specification-21-web-version#h.1v1yuxt) using LicenseRef-[ID] and LicenseText.

If there is interest in this approach, I'll see if I can come up with an example to add.

**Comment by pombredanne** [comment]
@goneall re:

> If this was intended to be primarily human read and/or written (e.g. like a configuration file), I would agree with YAML. I think this will be primarily read by tools so JSON may be a better choice.

I do not care too much about one or the other. That's just a data definition so we can use either one

**Comment by pombredanne** [comment]
@goneall re:

> We could add "local licenses" for each section into the document using the same terms as section 6.1 in the spec using LicenseRef-[ID] and LicenseText.

> If there is interest in this approach, I'll see if I can come up with an example to add.

That would help :+1:

**Comment by goneall** [comment]
From the SPDX call on 8 Oct, YAML is the preferred format due to it being more human readable and writable.

**Comment by goneall** [comment]
> We could add "local licenses" for each section into the document using the same terms as section 6.1 in the spec using LicenseRef-[ID] and LicenseText.

Here's an example.  Say we have a Maven POM file with the following license element:
```
<licenses>
  <license>
    <name>Android Software Development Kit License</name>
    <url>https://developer.android.com/studio/terms.html</url>
    <distribution>repo</distribution>
    <comments>This is non open source license</comments>
  </license>
</licenses>
```
The resultant mapping would be:
```
- package_type: maven
  declared_license:
    name: Android Software Development Kit License
    url: https://developer.android.com/studio/terms.html
  license_expression: LicenseRef-AndroidSDK
  notes: See https://maven.google.com/com/google/android/gms/play-services/12.0.0/play-services-12.0.0.pom
  local_licenses:
    - LicenseRef-AndroidSDK:
          ExtractedText: >
             This is the Android Software Development Kit License Agreement ...
          LicenseName: Android Software Development Kit License
          LicenseCrossReference: https://developer.android.com/studio/terms.html
          LicenseComment: This is non open source license
```
